bucketName: aubsbucket01
firstNames: firstNames.json
mongoSecretsName: mongo
mongoSecretsVersion: 3
realmSecretsName: realm
realmSecretsVersion: 2
databaseName: kasie_transie_db
doIndex: 0
mongoString: mongodb://localhost:27017
my-app-secret-1: ${sm://application-secret/latest}
placesAPIKeyName: places_api_key
projectId: thermal-effort-366015
secretsVersion: 2
requestsPerSecond: 20
server:
    connection-timeout: 90s
    max-http-header-size: 80KB
    tomcat:
        max-http-get-size: 4MB
        max-http-post-size: 4MB
        max-swallow-size: 4MB
        threads:
            max: 200
spring:
    main:
        allow-circular-references: true
    data:
        mongodb:
            database: kasie_transie_db

storageBucket: thermal-effort-366015.appspot.com
surnames: surnames.json
